### ISSUE TITLE
ubuntu have some issue as follow:

### ISSUE THREAD

**Issue by savior7w** [youngyangyang04/PowerVim#2]
Error detected while processing /home/alex/.vimrc:
line   42:
E197: Cannot set language to "zh_CN.gb2312"
macdown.vim only works on a Mac
Taglist: Exuberant ctags (http://ctags.sf.net) not found in PATH. Plugin is not loaded.
Mr Carl, could you please make the config file more general? thanks

**Comment by youngyangyang04** [comment]
> Error detected while processing /home/alex/.vimrc:
> line 42:
> E197: Cannot set language to "zh_CN.gb2312"
> macdown.vim only works on a Mac
> Taglist: Exuberant ctags (http://ctags.sf.net) not found in PATH. Plugin is not loaded.
> Mr Carl, could you please make the config file more general? thanks

Thank you for your suggestion, this problem has been fixed, just update the latest version

**Comment by 3481554467** [comment]
> > Error detected while processing /home/alex/.vimrc:
> > line 42:
> > E197: Cannot set language to "zh_CN.gb2312"
> > macdown.vim only works on a Mac
> > Taglist: Exuberant ctags (http://ctags.sf.net) not found in PATH. Plugin is not loaded.
> > Mr Carl, could you please make the config file more general? thanks
> 
> Thank you for your suggestion, this problem has been fixed, just update the latest version

处理 /home/x/.vimrc 时发生错误:
第   43 行:
E197: 不能设定语言为 "zh_CN.gb2312"
Taglist: Exuberant ctags (http://ctags.sf.net) not found in PATH. Plugin is not loaded.
请按 ENTER 或其它命令继续

一用vim就这样，而且现在终端不能输入中文了，怎么卸载pv？我只想简单在终端可以输入中文

**Comment by 3481554467** [comment]
> > > Error detected while processing /home/alex/.vimrc:
> > > line 42:
> > > E197: Cannot set language to "zh_CN.gb2312"
> > > macdown.vim only works on a Mac
> > > Taglist: Exuberant ctags (http://ctags.sf.net) not found in PATH. Plugin is not loaded.
> > > Mr Carl, could you please make the config file more general? thanks
> > 
> > 
> > Thank you for your suggestion, this problem has been fixed, just update the latest version
> 
> 处理 /home/x/.vimrc 时发生错误: 第 43 行: E197: 不能设定语言为 "zh_CN.gb2312" Taglist: Exuberant ctags (http://ctags.sf.net) not found in PATH. Plugin is not loaded. 请按 ENTER 或其它命令继续
> 
> 一用vim就这样，而且现在终端不能输入中文了，怎么卸载pv？我只想简单在终端可以输入中文

ubuntu22.04  i3
