### ISSUE TITLE
vi Demo.java

### ISSUE THREAD

**Issue by senkorl** [youngyangyang04/PowerVim#27]
"Demo.java" [New]
Error detected while processing BufNewFile Autocommands for "*.java"..FileType A
utocommands for "java"..script /Users/qqe/example/workspace/PowerVim/.vim/bund
le/vim-javacomplete2/autoload/javacomplete.vim:
line   18:
Javacomplete needs Python support to run!
Error detected while processing BufNewFile Autocommands for "*.java"..FileType A
utocommands for "java":
E117: Unknown function: javacomplete#Start

-----------------------
设备：m1 macbook air

**Comment by imperfect-wqy** [comment]
你好，解决了吗，如何解决的呀

**Comment by zhouyijiaren** [comment]
还没有解决吗？ 我也遇见了， intel macbook pro

**Comment by senkorl** [comment]
安装完之后 位置不要乱移动就行。

**Comment by zhouyijiaren** [comment]
我发现是vim没有装Feature： python导致的。
可以通过下面代码验证：
`vim --version | grep python`
如果是-。说明vim在安装的时候没有开启python选项。
可以把vim删掉，重新安装
