### ISSUE TITLE
Ubuntu18.04环境会报如下错误

### ISSUE THREAD

**Issue by kingsfar** [youngyangyang04/PowerVim#3]
Ubuntu18.04直接执行 sh install.sh会报install.sh: 8: install.sh: Syntax error: "(" unexpected，后来发现Ubuntu下sh默认指向dash（ls -l /bin/sh），需将sh指向bash可正常运行脚本（sudo dpkg-reconfigure dash），原因是：function在bash中为关键字，dash中没有function这个关键字。
另外，执行完脚本后使用vim会报如下错误：
处理 /home/wsy/.vimrc 时发生错误:
第   42 行:
E197: 不能设定语言为 "zh_CN.gb2312"
Taglist: Exuberant ctags (http://ctags.sf.net) not found in PATH. Plugin is not loaded.
请按 ENTER 或其它命令继续
请问carl哥怎么解决

**Comment by Winniekun** [comment]
> Ubuntu18.04直接执行 sh install.sh会报install.sh: 8: install.sh: Syntax error: "(" unexpected，后来发现Ubuntu下sh默认指向dash（ls -l /bin/sh），需将sh指向bash可正常运行脚本（sudo dpkg-reconfigure dash），原因是：function在bash中为关键字，dash中没有function这个关键字。
> 另外，执行完脚本后使用vim会报如下错误：
> 处理 /home/wsy/.vimrc 时发生错误:
> 第 42 行:
> E197: 不能设定语言为 "zh_CN.gb2312"
> Taglist: Exuberant ctags (http://ctags.sf.net) not found in PATH. Plugin is not loaded.
> 请按 ENTER 或其它命令继续
> 请问carl哥怎么解决

自告奋勇一下，应该系统语言问题，可以看下这个 [解决方式](https://gist.github.com/BoWang816/c2e9ce52ce03c59450bcf587b7d0f456) 😉

**Comment by kingsfar** [comment]
> > Ubuntu18.04直接执行 sh install.sh会报install.sh: 8: install.sh: Syntax error: "(" unexpected，后来发现Ubuntu下sh默认指向dash（ls -l /bin/sh），需将sh指向bash可正常运行脚本（sudo dpkg-reconfigure dash），原因是：function在bash中为关键字，dash中没有function这个关键字。
> > 另外，执行完脚本后使用vim会报如下错误：
> > 处理 /home/wsy/.vimrc 时发生错误:
> > 第 42 行:
> > E197: 不能设定语言为 "zh_CN.gb2312"
> > Taglist: Exuberant ctags (http://ctags.sf.net) not found in PATH. Plugin is not loaded.
> > 请按 ENTER 或其它命令继续
> > 请问carl哥怎么解决
> 
> 自告奋勇一下，应该系统语言问题，可以看下这个 [解决方式](https://gist.github.com/BoWang816/c2e9ce52ce03c59450bcf587b7d0f456)

确实是系统语言问题，解决了，谢谢~
至于第二行报错应该是taglist.vim插件的问题：在~/.vimrc 文件中加入如下三行就可以了
let Tlist_Show_One_File=1     "不同时显示多个文件的tag，只显示当前文件的  
let Tlist_Exit_OnlyWindow=1   "如果taglist窗口是最后一个窗口，则退出vim 
let Tlist_Ctags_Cmd="/usr/bin/ctags" "将taglist与ctags关联

**Comment by niu0217** [comment]
第一个问题https://blog.csdn.net/zachaway/article/details/25303767在这里可以解决  至于按enter报错，我按照楼主的还是不行

**Comment by Vitamin2020** [comment]
E197: Cannot set language to "zh_CN.GB2312"
用了CSDN 各种方法，依然没有解决

**Comment by Ricardio609** [comment]
请问可以不设置语言为zh_CN.gb2312吗？

**Comment by OrionZJ** [comment]
> 

我把这行代码注释了，目前还没有遇到使用问题

**Comment by snow-tyan** [comment]
所以直接/bin/bash install.sh?  
我这里执行完就打印下面，这是成功了吗😂
```shell
\033[0;35mStart to install vim-conf\033[0m
\033[0;36mLooking for an existing vim config...\033[0m
\033[0;36mCopying .vimrc and .vim\033[0m
\033[0;32mln -s /home/snow/.PowerVim/.vimrc .vimrc\033[0m
\033[0;32mln -s /home/snow/.PowerVim/.vim .vim\033[0m
\033[0;32mln -s /home/snow/.PowerVim/.ctags .ctags\033[0m
\033[0;35m  _____                    __      ___             \033[0m
\033[0;35m  |  __ \                   \ \    / (_)           \033[0m
\033[0;35m  | |__) |____      _____ _ _\ \  / / _ _ __ ___   \033[0m
\033[0;35m  |  ___/ _ \ \ /\ / / _ \ \__\ \/ / | |  _   _ \  \033[0m
\033[0;35m  | |  | (_) \ V  V /  __/ /   \  /  | | | | | | | \033[0m
\033[0;35m  |_|   \___/ \_/\_/ \___|_|    \/   |_|_| |_| |_| \033[0m
\n\n \033[0;35mEnjoy!.\033[0m
```

**Comment by snow-tyan** [comment]
安装算是成功了，但是之前报的缺少"("的错，感觉并没有解决，我在输入左右括号时，会多补全一个右括号

**Comment by chumingqian** [comment]
我也遇到这个错误， 但是 ， 我 执行 bash install.sh   就可以安装了；

**Comment by O-l-d-C-a-t** [comment]
> E197: Cannot set language to "zh_CN.GB2312" 用了CSDN 各种方法，依然没有解决

可以查看该解决办法，亲测有效，从开始到sudo locale-gen就可以
https://gist.github.com/BoWang816/c2e9ce52ce03c59450bcf587b7d0f456

**Comment by liquidhiter** [comment]
小白一枚，win11下wsl2环境中个人解决方法如下:
1> $ ./install.sh, (好奇install.sh首行不是已经添加了shebang，直接运行install.sh系统不是应该自动识别使用bash运行吗？)
2> 使用vim编辑.vimrc文件注释掉设置语言的两行(em，懒人解决方法:)
使用vim如果遇到错误提示：`Taglist: Exuberant ctags (http://ctags.sf.net) not found in PATH. Plugin is not loaded`，需要额外安装` sudo apt-get install exuberant-ctags`

**Comment by dqxcj** [comment]
ubuntu20.04环境，总结一下我使用的各位老哥的解决方法
第一个问题，使用/bin/bash install.sh
第二个问题第一问，https://gist.github.com/BoWang816/c2e9ce52ce03c59450bcf587b7d0f456
第二个问题第二问，在~/.vimrc 文件中加入如下三行:
              let Tlist_Show_One_File=1 "不同时显示多个文件的tag，只显示当前文件的
              let Tlist_Exit_OnlyWindow=1 "如果taglist窗口是最后一个窗口，则退出vim
              let Tlist_Ctags_Cmd="/usr/bin/ctags" "将taglist与ctags关联
