### ISSUE TITLE
从系统剪切板粘贴代码块时，会奇怪的插入tab和后缀

### ISSUE THREAD

**Issue by ShuaidongGG** [youngyangyang04/PowerVim#49]
如题
复制前

```
# add to ~/.bashrc

PROXY_HTTP="http://127.0.0.1:7890"
p-on(){
    export http_proxy="${PROXY_HTTP}"
    export HTTP_PROXY="${PROXY_HTTP}"
    export https_proxy="${PROXY_HTTP}"
    export HTTPS_proxy="${PROXY_HTTP}"
    git config --global http.proxy "${PROXY_HTTP}"
    git config --global https.proxy "${PROXY_HTTP}"
echo "proxy on"
}
 
p-off(){
    unset http_proxy
    unset HTTP_PROXY
    unset https_proxy
    unset HTTPS_PROXY
    git config --global --unset http.proxy
    git config --global --unset https.proxy
echo "proxy off"
}
```

复制后

![image](https://github.com/youngyangyang04/PowerVim/assets/101390231/3c7c0e91-2785-4d87-bd6f-f85f27c9f248)

**Comment by sycice** [comment]
确实我也遇到这个问题了，然后各种改vimrc配置也没用，最后全删了就好了，这样也用不了这个powervim了呀

**Comment by ShuaidongGG** [comment]
> 确实我也遇到这个问题了，然后各种改vimrc配置也没用，最后全删了就好了，这样也用不了这个powervim了呀

我们可能需要MorePowerVim :)

**Comment by sycice** [comment]
解决了 你要粘贴的时候 进command模式然后  :set paste 然后在粘贴就不会乱码了

**Comment by ShuaidongGG** [comment]
> 解决了 你要粘贴的时候 进command模式然后 :set paste 然后在粘贴就不会乱码了

非常感谢，具体复制过程为 从主机复制内容 -> 到虚拟机中vim 打开一个脚本 -> 键入 `:set paste` -> 进入写入模式 -> `ctrl + shift + v` 组合粘贴
